# Generated by Django 5.0 on 2023-12-25 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_factory_user_user_factory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="factory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipments",
                to="core.factory",
            ),
        ),
    ]
